'use client'
import './globals.scss'
import React from "react";
import {createTheme, ThemeProvider} from "@mui/material";
import {Provider} from "react-redux";
import {store, persistor} from "@component/store/store";
import styles from './styles.module.css'
import {Header} from "@component/components/Header/Header";
import {Footer} from "@component/components/Footer/Footer";
import {PersistGate} from "redux-persist/integration/react";
import {useAppSelector} from "@component/hooks/hooks";

// const inter = Inter({subsets: ['latin']})

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {

    const theme = createTheme({
        palette: {
            primary: {
                main: '#212121',
            },
            secondary: {
                main: '#eeeeee',
            },
        },
    });



    return (
        <html lang="en">
        <body className={styles.container}>
        <ThemeProvider theme={theme}>
            <Provider store={store}>
                <PersistGate persistor={persistor} loading={null}>
                    <Header className={styles.header}/>
                    <main className={styles.main}>
                        {children}
                    </main>
                    <Footer className={styles.footer}/>
                </PersistGate>
            </Provider>
        </ThemeProvider>
        </body>
        </html>
    )
}
